import type { Component } from 'vue';
import {
  AccountBookOutlined,
  AlertOutlined,
  AlignLeftOutlined,
  ApiOutlined,
  AudioMutedOutlined,
  AppstoreOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BlockOutlined,
  BranchesOutlined,
  BugOutlined,
  BulbOutlined,
  CalendarOutlined,
  CarOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  ChromeOutlined,
  ClockCircleOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudUploadOutlined,
  CodeOutlined,
  CodeSandboxOutlined,
  CommentOutlined,
  ContainerOutlined,
  ControlOutlined,
  CloseCircleOutlined,
  CopyOutlined,
  CreditCardOutlined,
  CrownOutlined,
  DashboardFilled,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DeploymentUnitOutlined,
  DollarOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  EyeOutlined,
  FallOutlined,
  FileOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FullscreenOutlined,
  FundOutlined,
  FundProjectionScreenOutlined,
  GatewayOutlined,
  GlobalOutlined,
  GoldOutlined,
  ExportOutlined,
  HeartOutlined,
  HighlightOutlined,
  HistoryOutlined,
  KeyOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  MobileOutlined,
  MonitorOutlined,
  MoneyCollectOutlined,
  NodeIndexOutlined,
  OrderedListOutlined,
  PauseOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  ProjectOutlined,
  QuestionCircleOutlined,
  RadarChartOutlined,
  ReadOutlined,
  ReloadOutlined,
  RiseOutlined,
  RocketOutlined,
  RobotOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SendOutlined,
  SettingOutlined,
  ShopOutlined,
  ShoppingOutlined,
  SoundOutlined,
  StarOutlined,
  SwapOutlined,
  SyncOutlined,
  UnorderedListOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UserAddOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WarningOutlined,
} from '@ant-design/icons-vue';

/** 侧栏 / 搜索 / 卡片统一图标解析（禁止 emoji 作 icon） */
export const antIconMap: Record<string, Component> = {
  DashboardOutlined,
  PauseOutlined,
  ShoppingOutlined,
  FolderOpenOutlined,
  SearchOutlined,
  FileTextOutlined,
  FundOutlined,
  FundProjectionScreenOutlined,
  AuditOutlined,
  CopyOutlined,
  FileOutlined,
  PictureOutlined,
  MessageOutlined,
  UserOutlined,
  BarChartOutlined,
  SettingOutlined,
  CrownOutlined,
  ExperimentOutlined,
  CodeOutlined,
  SafetyOutlined,
  ThunderboltOutlined,
  LockOutlined,
  ToolOutlined,
  AppstoreOutlined,
  CommentOutlined,
  CarryOutOutlined,
  BulbOutlined,
  SyncOutlined,
  BugOutlined,
  AlignLeftOutlined,
  FolderOutlined,
  DatabaseOutlined,
  HistoryOutlined,
  SecurityScanOutlined,
  WarningOutlined,
  FileSearchOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  PlayCircleOutlined,
  CalendarOutlined,
  BranchesOutlined,
  MonitorOutlined,
  ApiOutlined,
  EnvironmentOutlined,
  SendOutlined,
  EyeOutlined,
  HighlightOutlined,
  LineChartOutlined,
  GlobalOutlined,
  ControlOutlined,
  ReadOutlined,
  SafetyCertificateOutlined,
  LinkOutlined,
  CloudOutlined,
  RobotOutlined,
  VideoCameraOutlined,
  TranslationOutlined,
  CarOutlined,
  HeartOutlined,
  TeamOutlined,
  NodeIndexOutlined,
  CloudServerOutlined,
  CodeSandboxOutlined,
  SoundOutlined,
  OrderedListOutlined,
  PayCircleOutlined,
  ProjectOutlined,
  ShopOutlined,
  BankOutlined,
  RadarChartOutlined,
  RedditCircleFilled: DashboardFilled,
  DeploymentUnitOutlined,
  GatewayOutlined,
  BlockOutlined,
  PartitionOutlined,
  GoldOutlined,
  TrophyOutlined,
  RiseOutlined,
  FallOutlined,
  AlertOutlined,
  ReloadOutlined,
  DashboardFilled,
  DollarOutlined,
  UserAddOutlined,
  EditOutlined,
  MailOutlined,
  AccountBookOutlined,
  CreditCardOutlined,
  PhoneOutlined,
  SwapOutlined,
  GridOutlined: AppstoreOutlined,
  BrainOutlined: ExperimentOutlined,
  ShieldOutlined: SafetyOutlined,
  ZapOutlined: ThunderboltOutlined,
  WrenchOutlined: ToolOutlined,
  MessageSquareOutlined: CommentOutlined,
  TaskSquareOutlined: CarryOutOutlined,
  SparklesOutlined: BulbOutlined,
  RepeatOutlined: SyncOutlined,
  ToolsOutlined: ToolOutlined,
  FilesOutlined: FolderOutlined,
  AlertTriangleOutlined: WarningOutlined,
  TimerOutlined: ClockCircleOutlined,
  GitBranchOutlined: BranchesOutlined,
  CpuOutlined: ApiOutlined,
  AudioOutlined: SoundOutlined,
  RocketOutlined,
  CompassOutlined: GlobalOutlined,
  TruckOutlined: CarOutlined,
  BuildOutlined: ToolOutlined,
  ClusterOutlined: CloudServerOutlined,
  SubnodeOutlined: NodeIndexOutlined,
  ReconciliationOutlined: CheckCircleOutlined,
  CalculatorOutlined: BankOutlined,
  DeleteOutlined,
  SaveOutlined,
  FormOutlined,
  FullscreenOutlined,
  ExportOutlined,
  MenuOutlined,
  MobileOutlined,
  QuestionCircleOutlined,
  StarOutlined,
  UnorderedListOutlined,
  AudioMutedOutlined,
  CloseCircleOutlined,
  ChromeOutlined,
  CloudUploadOutlined,
  ContainerOutlined,
  KeyOutlined,
  LayoutOutlined,
  MoneyCollectOutlined,
  PercentageOutlined,
  FunnelPlotOutlined: BarChartOutlined,
  AimOutlined: RocketOutlined,
  TargetOutlined: RocketOutlined,
  ApartmentOutlined: TeamOutlined,
  SpiderOutlined: BugOutlined,
  BuildingOutlined: CloudServerOutlined,
  ServerOutlined: CloudServerOutlined,
  AwardOutlined: TrophyOutlined,
  LayersOutlined: AppstoreOutlined,
  MagicOutlined: BulbOutlined,
  MapOutlined: EnvironmentOutlined,
  PackageOutlined: ShopOutlined,
  SettingsOutlined: SettingOutlined,
};

export function resolveAntIcon(name?: string): Component {
  if (!name) return DashboardOutlined;
  return antIconMap[name] || DashboardOutlined;
}

/** 三区治理 / 快捷入口：path → Ant 图标名 */
export const routeIconByPath: Record<string, string> = {
  '/admin/dashboard': 'DashboardOutlined',
  '/client/traffic': 'LineChartOutlined',
  '/admin/traffic-board': 'BarChartOutlined',
  '/admin/tenants': 'TeamOutlined',
  '/inquiries': 'MessageOutlined',
  '/admin/scheduler-hub': 'SendOutlined',
  '/admin/finance': 'AccountBookOutlined',
  '/admin/finance/payment-ops': 'PayCircleOutlined',
  '/admin/finance/invoices': 'FileTextOutlined',
  '/admin/finance/commissions': 'DollarOutlined',
  '/admin/finance/commission-rules': 'SettingOutlined',
  '/admin/aggregation': 'BarChartOutlined',
  '/referral': 'TrophyOutlined',
  '/admin/system': 'SettingOutlined',
  '/admin/ai-engine/trade-intel': 'GlobalOutlined',
  '/admin/ai-engine': 'ApiOutlined',
  '/admin/demo-rehearsal': 'PlayCircleOutlined',
  '/system-health': 'HeartOutlined',
  '/system-health/dashboard': 'HeartOutlined',
  '/admin/v2ray': 'LinkOutlined',
  '/agent-hub': 'RobotOutlined',
  '/agent-hub/dashboard': 'RobotOutlined',
  '/client/product-images': 'PictureOutlined',
  '/client/video-space': 'VideoCameraOutlined',
  '/admin/video-space': 'VideoCameraOutlined',
  '/admin/file-manager': 'PictureOutlined',
  '/media-factory/dashboard': 'VideoCameraOutlined',
  '/admin': 'CrownOutlined',
  '/client/dashboard': 'DashboardOutlined',
};

export function iconNameForPath(path: string): string {
  return routeIconByPath[path] || 'AppstoreOutlined';
}
