/**
 * Copyright (c) 2026 吕博旺 (131025199403304817). All rights reserved.
 */
/** 超级管理员工作台能力项（与路由 path 对齐，供按级别划拨与过滤） */

export type WorkbenchTone =
  | 'sky'
  | 'violet'
  | 'amber'
  | 'emerald'
  | 'rose'
  | 'cyan'
  | 'indigo'
  | 'slate'
  | 'pink'
  | 'teal'
  | 'blue'
  | 'orange'
  | 'red'
  | 'green'
  | 'purple';

export interface WorkbenchItemDef {
  id: string;
  path: string;
  name: string;
  description: string;
  tone: WorkbenchTone;
  itemIcon: string;
  /** 首页顶部快捷瓷片（与原先 quickEntries 对齐） */
  quick?: boolean;
  /** 仅参与路由守卫与划拨，不在工作台卡片区展示 */
  guardOnly?: boolean;
}

export interface WorkbenchSectionDef {
  key: string;
  title: string;
  subtitle: string;
  tone: WorkbenchTone;
  sectionIcon: string;
  items: WorkbenchItemDef[];
}

export const WORKBENCH_CAPABILITY_REGISTRY: WorkbenchSectionDef[] = [
  {
    key: 'core',
    title: '控制台与业务',
    subtitle: '日常运营、内容与获客',
    tone: 'sky',
    sectionIcon: 'DashboardOutlined',
    items: [
      {
        id: 'core.dashboard',
        path: '/dashboard',
        name: '数据概览',
        description: '核心指标与 SEO 仪表盘',
        tone: 'sky',
        itemIcon: 'DashboardOutlined',
        quick: true,
      },
      {
        id: 'core.products',
        path: '/products',
        name: '产品列表',
        description: '产品与规格维护',
        tone: 'violet',
        itemIcon: 'ShoppingOutlined',
        quick: true,
      },
      {
        id: 'core.categories',
        path: '/products/categories',
        name: '分类管理',
        description: '产品分类与树形结构',
        tone: 'amber',
        itemIcon: 'FolderOpenOutlined',
      },
      {
        id: 'core.content',
        path: '/content',
        name: '内容管理',
        description: '页面与文案内容',
        tone: 'emerald',
        itemIcon: 'FileOutlined',
      },
      {
        id: 'core.cases',
        path: '/cases',
        name: '案例管理',
        description: '成功案例展示',
        tone: 'rose',
        itemIcon: 'PictureOutlined',
      },
      {
        id: 'core.inquiries',
        path: '/inquiries',
        name: '询盘管理',
        description: '线索与客户询盘',
        tone: 'cyan',
        itemIcon: 'MessageOutlined',
        quick: true,
      },
      {
        id: 'core.news',
        path: '/news',
        name: '新闻管理',
        description: '新闻资讯（API §6）',
        tone: 'indigo',
        itemIcon: 'ReadOutlined',
        quick: true,
      },
    ],
  },
  {
    key: 'seo',
    title: 'SEO 工具箱',
    subtitle: '站内优化、合规与排名',
    tone: 'violet',
    sectionIcon: 'SearchOutlined',
    items: [
      {
        id: 'seo.overview',
        path: '/seo',
        name: 'SEO 概览',
        description: 'SEO 总览与快捷入口',
        tone: 'violet',
        itemIcon: 'SearchOutlined',
      },
      {
        id: 'seo.batch',
        path: '/seo/batch-seo',
        name: '批量 SEO',
        description: '批量页面元数据',
        tone: 'indigo',
        itemIcon: 'CopyOutlined',
      },
      {
        id: 'seo.optimizer',
        path: '/seo/content-optimizer',
        name: 'AI 内容优化',
        description: '智能优化正文与标题',
        tone: 'pink',
        itemIcon: 'HighlightOutlined',
      },
      {
        id: 'seo.llms',
        path: '/seo/llms-txt',
        name: 'LLMs.txt',
        description: '生成 LLMs 可见性文件',
        tone: 'teal',
        itemIcon: 'FileTextOutlined',
      },
      {
        id: 'seo.audit',
        path: '/seo/site-audit',
        name: '站点审计',
        description: '技术 SEO 巡检',
        tone: 'orange',
        itemIcon: 'AuditOutlined',
      },
      {
        id: 'seo.schema',
        path: '/seo/schema-markup',
        name: 'Schema 标记',
        description: '结构化数据管理',
        tone: 'blue',
        itemIcon: 'CodeOutlined',
      },
      {
        id: 'seo.eeat',
        path: '/seo/eeat',
        name: 'EEAT 评分',
        description: '经验权威可信度',
        tone: 'emerald',
        itemIcon: 'SafetyOutlined',
      },
      {
        id: 'seo.compliance',
        path: '/seo/compliance',
        name: '广告法合规',
        description: '敏感词与合规扫描',
        tone: 'amber',
        itemIcon: 'WarningOutlined',
      },
      {
        id: 'seo.ranking',
        path: '/seo/keyword-ranking',
        name: '关键词排名',
        description: '排名追踪与历史',
        tone: 'sky',
        itemIcon: 'LineChartOutlined',
      },
      {
        id: 'seo.performance',
        path: '/seo/performance',
        name: '性能与安全',
        description: '监控与健康检查',
        tone: 'slate',
        itemIcon: 'GlobalOutlined',
      },
    ],
  },
  {
    key: 'matrix',
    title: 'SEO 矩阵系统',
    subtitle: '地域词、生成、分发与收录',
    tone: 'indigo',
    sectionIcon: 'AppstoreOutlined',
    items: [
      {
        id: 'matrix.dashboard',
        path: '/seo-matrix',
        name: '矩阵看板',
        description: '矩阵总览与任务',
        tone: 'indigo',
        itemIcon: 'DashboardOutlined',
        quick: true,
      },
      {
        id: 'matrix.settings',
        path: '/seo-matrix/settings',
        name: '系统设置',
        description: '矩阵全局参数',
        tone: 'slate',
        itemIcon: 'SettingOutlined',
      },
      {
        id: 'matrix.regions',
        path: '/seo-matrix/regions',
        name: '地域词库',
        description: '省市区与词组',
        tone: 'emerald',
        itemIcon: 'EnvironmentOutlined',
      },
      {
        id: 'matrix.keywords',
        path: '/seo-matrix/keywords',
        name: '关键词管理',
        description: '组合与生成词',
        tone: 'violet',
        itemIcon: 'SearchOutlined',
      },
      {
        id: 'matrix.content',
        path: '/seo-matrix/content',
        name: '文案生成',
        description: '模板与批量文案',
        tone: 'sky',
        itemIcon: 'FileTextOutlined',
      },
      {
        id: 'matrix.publish',
        path: '/seo-matrix/publish',
        name: '多平台分发',
        description: '发布任务与账号',
        tone: 'rose',
        itemIcon: 'SendOutlined',
      },
      {
        id: 'matrix.inclusion',
        path: '/seo-matrix/inclusion',
        name: '收录监控',
        description: '收录状态与复检',
        tone: 'cyan',
        itemIcon: 'EyeOutlined',
      },
      {
        id: 'matrix.growth-tools',
        path: '/seo-matrix/growth-tools',
        name: '增长工具',
        description: '热词库、内容质检与 AI 流量',
        tone: 'amber',
        itemIcon: 'ToolOutlined',
      },
    ],
  },
  {
    key: 'system',
    title: '系统与设置',
    subtitle: '账号、分析与站点配置',
    tone: 'slate',
    sectionIcon: 'SettingOutlined',
    items: [
      {
        id: 'system.users',
        path: '/users',
        name: '用户管理',
        description: '后台用户与角色',
        tone: 'blue',
        itemIcon: 'UserOutlined',
        quick: true,
      },
      {
        id: 'system.analytics',
        path: '/analytics',
        name: '数据分析',
        description: '统计与审计日志',
        tone: 'violet',
        itemIcon: 'BarChartOutlined',
      },
      {
        id: 'system.settings',
        path: '/settings',
        name: '基本设置',
        description: '站点与参数',
        tone: 'slate',
        itemIcon: 'SettingOutlined',
      },
      {
        id: 'system.drag',
        path: '/settings/drag-module',
        name: '拖拽模块',
        description: '首页模块编排',
        tone: 'amber',
        itemIcon: 'ControlOutlined',
      },
      {
        id: 'system.effects',
        path: '/settings/effects',
        name: '特效组件',
        description: '动效与展示组件',
        tone: 'pink',
        itemIcon: 'HighlightOutlined',
      },
    ],
  },
  {
    key: 'platform',
    title: '平台集成与治理',
    subtitle: 'AI 配置、实验、飞书与全局合规',
    tone: 'emerald',
    sectionIcon: 'SafetyCertificateOutlined',
    items: [
      {
        id: 'platform.compliance',
        path: '/compliance',
        name: '合规治理中心',
        description: '全局合规分数与问题单',
        tone: 'emerald',
        itemIcon: 'SafetyCertificateOutlined',
        quick: true,
      },
      {
        id: 'platform.ai',
        path: '/ai-config',
        name: 'AI 配置',
        description: '提供商、默认模型与统计',
        tone: 'violet',
        itemIcon: 'ApiOutlined',
      },
      {
        id: 'platform.ab',
        path: '/ab-test',
        name: 'A/B 测试',
        description: '实验生命周期管理',
        tone: 'purple',
        itemIcon: 'ExperimentOutlined',
      },
      {
        id: 'platform.feishu',
        path: '/feishu',
        name: '飞书集成',
        description: '绑定状态与消息日志',
        tone: 'blue',
        itemIcon: 'LinkOutlined',
      },
    ],
  },
  {
    key: 'suite',
    title: '超级管理员套件',
    subtitle: '系统底层、AI、代码、文件、安全与自动化',
    tone: 'purple',
    sectionIcon: 'ControlOutlined',
    items: [
      {
        id: 'suite.workbench',
        path: '/admin',
        name: '工作台根路径',
        description: '路由守卫：访问 /admin 功能总览页所需能力（不在工作台重复展示）',
        tone: 'purple',
        itemIcon: 'CrownOutlined',
        guardOnly: true,
      },
      {
        id: 'suite.capability',
        path: '/admin/capability-hub',
        name: '能力导航',
        description: '路线图子页、后端/本地数据来源说明',
        tone: 'purple',
        itemIcon: 'PartitionOutlined',
        quick: true,
      },
      {
        id: 'suite.sys-overview',
        path: '/admin/system',
        name: '系统概览',
        description: '运行状态与资源',
        tone: 'sky',
        itemIcon: 'MonitorOutlined',
      },
      {
        id: 'suite.sys-users',
        path: '/admin/system/users',
        name: '套件用户管理',
        description: '管理员套件内用户视图',
        tone: 'blue',
        itemIcon: 'UserOutlined',
      },
      {
        id: 'suite.permissions',
        path: '/admin/system/permissions',
        name: '权限管理',
        description: '角色与权限矩阵',
        tone: 'orange',
        itemIcon: 'LockOutlined',
      },
      {
        id: 'suite.agent-cap',
        path: '/admin/system/agent-capabilities',
        name: '代理能力划拨',
        description: '五级代理蓝图 + 按级别勾选工作台（本地配置）',
        tone: 'purple',
        itemIcon: 'PartitionOutlined',
      },
      {
        id: 'suite.hierarchy',
        path: '/admin/hierarchy',
        name: '层级管理',
        description: '超管→省级→市级→租户 四级管理架构',
        tone: 'violet',
        itemIcon: 'AppstoreOutlined',
        quick: true,
      },
      {
        id: 'suite.logs',
        path: '/admin/system/logs',
        name: '系统日志',
        description: '操作与审计',
        tone: 'slate',
        itemIcon: 'FileTextOutlined',
      },
      {
        id: 'suite.config',
        path: '/admin/system/config',
        name: '系统配置',
        description: '环境参数',
        tone: 'amber',
        itemIcon: 'ToolOutlined',
      },
      {
        id: 'suite.ai',
        path: '/admin/ai-center',
        name: 'AI 引擎概览',
        description: '模型与调用',
        tone: 'violet',
        itemIcon: 'ApiOutlined',
      },
      {
        id: 'suite.models',
        path: '/admin/ai-center/models',
        name: '模型管理',
        description: '模型与版本',
        tone: 'indigo',
        itemIcon: 'AppstoreOutlined',
      },
      {
        id: 'suite.prompts',
        path: '/admin/ai-center/prompts',
        name: '提示词管理',
        description: 'Prompt 模板',
        tone: 'pink',
        itemIcon: 'CommentOutlined',
      },
      {
        id: 'suite.ai-tasks',
        path: '/admin/ai-center/tasks',
        name: 'AI 任务',
        description: '任务队列',
        tone: 'teal',
        itemIcon: 'CarryOutOutlined',
      },
      {
        id: 'suite.ai-analytics',
        path: '/admin/ai-center/analytics',
        name: 'AI 分析',
        description: '调用统计',
        tone: 'blue',
        itemIcon: 'BarChartOutlined',
      },
      {
        id: 'suite.ai-usage',
        path: '/admin/ai-center/usage',
        name: '用量监控',
        description: 'Token 消耗与配额告警',
        tone: 'green',
        itemIcon: 'BarChartOutlined',
      },
      {
        id: 'suite.ai-provider-setup',
        path: '/admin/ai-center/provider-setup',
        name: '模型配置',
        description: 'AI大模型平台接入引导',
        tone: 'violet',
        itemIcon: 'ApiOutlined',
      },
      {
        id: 'suite.code',
        path: '/admin/code-tools',
        name: '代码工具概览',
        description: '开发者工具入口',
        tone: 'emerald',
        itemIcon: 'CodeOutlined',
      },
      {
        id: 'suite.gen',
        path: '/admin/code-tools/generator',
        name: '代码生成',
        description: '脚手架与片段',
        tone: 'amber',
        itemIcon: 'BulbOutlined',
      },
      {
        id: 'suite.refactor',
        path: '/admin/code-tools/refactor',
        name: '代码重构',
        description: '重构建议',
        tone: 'sky',
        itemIcon: 'SyncOutlined',
      },
      {
        id: 'suite.debug',
        path: '/admin/code-tools/debug',
        name: '代码调试',
        description: '调试辅助',
        tone: 'rose',
        itemIcon: 'BugOutlined',
      },
      {
        id: 'suite.format',
        path: '/admin/code-tools/format',
        name: '代码格式化',
        description: '风格统一',
        tone: 'slate',
        itemIcon: 'AlignLeftOutlined',
      },
      {
        id: 'suite.scan',
        path: '/admin/code-tools/scanner',
        name: '代码扫描',
        description: '安全与依赖扫描',
        tone: 'cyan',
        itemIcon: 'SearchOutlined',
      },
      {
        id: 'suite.review',
        path: '/admin/code-tools/review',
        name: '代码审查',
        description: '问题清单与修复建议',
        tone: 'rose',
        itemIcon: 'FileSearchOutlined',
      },
      {
        id: 'suite.files',
        path: '/admin/file-manager',
        name: '产品图片空间',
        description: '产品白底图 · 建站复用',
        tone: 'orange',
        itemIcon: 'PictureOutlined',
      },
      {
        id: 'suite.file-scan',
        path: '/admin/file-manager/scan',
        name: '文件扫描',
        description: '目录扫描',
        tone: 'cyan',
        itemIcon: 'SearchOutlined',
      },
      {
        id: 'suite.file-search',
        path: '/admin/file-manager/search',
        name: '全局检索',
        description: '跨文件搜索',
        tone: 'blue',
        itemIcon: 'DatabaseOutlined',
      },
      {
        id: 'suite.file-history',
        path: '/admin/file-manager/history',
        name: '文件历史',
        description: '变更记录',
        tone: 'slate',
        itemIcon: 'HistoryOutlined',
      },
      {
        id: 'suite.sec',
        path: '/admin/security',
        name: '安全概览',
        description: '风险总览',
        tone: 'red',
        itemIcon: 'SecurityScanOutlined',
      },
      {
        id: 'suite.vuln',
        path: '/admin/security/vulnerability',
        name: '漏洞扫描',
        description: '依赖与代码扫描',
        tone: 'orange',
        itemIcon: 'WarningOutlined',
      },
      {
        id: 'suite.sec-audit',
        path: '/admin/security/audit',
        name: '安全审计',
        description: '安全事件',
        tone: 'violet',
        itemIcon: 'FileSearchOutlined',
      },
      {
        id: 'suite.sec-comp',
        path: '/admin/security/compliance',
        name: '合规检查',
        description: '策略合规',
        tone: 'emerald',
        itemIcon: 'CheckCircleOutlined',
      },
      {
        id: 'suite.auto',
        path: '/admin/automation',
        name: '自动化概览',
        description: '任务总览',
        tone: 'amber',
        itemIcon: 'ThunderboltOutlined',
        quick: true,
      },
      {
        id: 'suite.scripts',
        path: '/admin/automation/scripts',
        name: '脚本管理',
        description: '脚本库',
        tone: 'green',
        itemIcon: 'PlayCircleOutlined',
      },
      {
        id: 'suite.sched',
        path: '/admin/automation/scheduler',
        name: '任务调度',
        description: 'Cron 与计划',
        tone: 'sky',
        itemIcon: 'CalendarOutlined',
      },
      {
        id: 'suite.flow',
        path: '/admin/automation/workflows',
        name: '工作流',
        description: '流程编排',
        tone: 'purple',
        itemIcon: 'BranchesOutlined',
      },
      {
        id: 'suite.projects',
        path: '/admin/projects',
        name: '项目概览',
        description: '多项目视图',
        tone: 'sky',
        itemIcon: 'FolderOutlined',
      },
      {
        id: 'suite.runtime',
        path: '/admin/runtime',
        name: '运行概览',
        description: '运行时与实例',
        tone: 'slate',
        itemIcon: 'CloudOutlined',
      },
      {
        id: 'suite.hub',
        path: '/admin/scheduler-hub',
        name: '调度概览',
        description: '集中调度看板',
        tone: 'amber',
        itemIcon: 'CalendarOutlined',
      },
    ],
  },
  {
    key: 'extended',
    title: '侧栏扩展域',
    subtitle: '演示/规划能力为主，可按级别裁剪',
    tone: 'slate',
    sectionIcon: 'NodeIndexOutlined',
    items: [
      {
        id: 'ext.annex-trade-ai',
        path: '/admin/annex/trade-ai',
        name: 'TradeAI 执行台',
        description: '附属一接入：AI 营销执行台（Lab）',
        tone: 'orange',
        itemIcon: 'ThunderboltOutlined',
      },
      {
        id: 'ext.annex-goodjob',
        path: '/admin/annex/goodjob',
        name: 'GoodJob 执行台',
        description: '附属二接入：外贸 CRM 执行台（Lab）',
        tone: 'cyan',
        itemIcon: 'GlobalOutlined',
      },
      {
        id: 'ext.agent',
        path: '/agent-hub',
        name: '智能体协同',
        description: 'MCP 桥接、任务编排与执行复盘',
        tone: 'violet',
        itemIcon: 'RobotOutlined',
      },
      {
        id: 'ext.media',
        path: '/media-factory',
        name: '视频生成工厂',
        description: 'TTS、图表与渲染队列',
        tone: 'rose',
        itemIcon: 'VideoCameraOutlined',
      },
      {
        id: 'ext.i18n',
        path: '/globalization',
        name: '多语言管理',
        description: '术语库、翻译与文化适配',
        tone: 'sky',
        itemIcon: 'TranslationOutlined',
      },
      {
        id: 'ext.logistics',
        path: '/logistics',
        name: '智能物流',
        description: 'LBS、运费与报价单',
        tone: 'amber',
        itemIcon: 'CarOutlined',
      },
      {
        id: 'ext.health',
        path: '/system-health',
        name: '系统健康压测',
        description: '压测、资源监控与备份',
        tone: 'emerald',
        itemIcon: 'HeartOutlined',
      },
      {
        id: 'ext.learn',
        path: '/ai-learning',
        name: 'AI 学习看板',
        description: '行为、漏斗与 A/B 自动化',
        tone: 'indigo',
        itemIcon: 'BulbOutlined',
      },
      {
        id: 'ext.tenants',
        path: '/tenants',
        name: '多租户中心',
        description: '套餐、计费与白标',
        tone: 'blue',
        itemIcon: 'TeamOutlined',
      },
      {
        id: 'ext.cognitive',
        path: '/cognitive',
        name: '认知与知识图谱',
        description: '问答、专家系统与语义索引',
        tone: 'cyan',
        itemIcon: 'NodeIndexOutlined',
      },
      {
        id: 'ext.cdn',
        path: '/edge-cdn',
        name: '边缘 CDN',
        description: '节点、预热与协议',
        tone: 'slate',
        itemIcon: 'CloudServerOutlined',
      },
      {
        id: 'ext.dev',
        path: '/developer',
        name: '开发者生态',
        description: 'API 网关、SDK、低代码与插件',
        tone: 'purple',
        itemIcon: 'CodeSandboxOutlined',
      },
    ],
  },
];

export function allCapabilityIds(): string[] {
  return WORKBENCH_CAPABILITY_REGISTRY.flatMap((s) => s.items.map((i) => i.id));
}
