"""add globalization international tenant payment tables

Revision ID: 4188869502e0
Revises: 016_add_ai_config_tables
Create Date: 2026-05-21 09:24:29.822195

"""
from typing import Sequence, Union
from alembic import op

def _uuid_col():
    """P0-B canonical：PG=native uuid（对齐模型 UUID_TYPE），其余=String(36)。"""
    if op.get_context().dialect.name == "postgresql":
        from sqlalchemy.dialects.postgresql import UUID

        return UUID(as_uuid=False)
    return sa.String(36)

import sqlalchemy as sa


revision: str = '4188869502e0'
down_revision: Union[str, None] = '016_add_ai_config_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _user_id_type():
    if op.get_context().dialect.name == "postgresql":
        from sqlalchemy.dialects.postgresql import UUID

        return UUID(as_uuid=True)
    return sa.String(length=36)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('zh', sa.String(length=200), nullable=False),
    sa.Column('en', sa.String(length=200), nullable=False),
    sa.Column('ja', sa.String(length=200), nullable=True),
    sa.Column('ko', sa.String(length=200), nullable=True),
    sa.Column('de', sa.String(length=200), nullable=True),
    sa.Column('fr', sa.String(length=200), nullable=True),
    sa.Column('es', sa.String(length=200), nullable=True),
    sa.Column('pt', sa.String(length=200), nullable=True),
    sa.Column('it', sa.String(length=200), nullable=True),
    sa.Column('nl', sa.String(length=200), nullable=True),
    sa.Column('ru', sa.String(length=200), nullable=True),
    sa.Column('ar', sa.String(length=200), nullable=True),
    sa.Column('tr', sa.String(length=200), nullable=True),
    sa.Column('fa', sa.String(length=200), nullable=True),
    sa.Column('he', sa.String(length=200), nullable=True),
    sa.Column('th', sa.String(length=200), nullable=True),
    sa.Column('vi', sa.String(length=200), nullable=True),
    sa.Column('ms', sa.String(length=200), nullable=True),
    sa.Column('hi', sa.String(length=200), nullable=True),
    sa.Column('id_ba', sa.String(length=200), nullable=True),
    sa.Column('tl', sa.String(length=200), nullable=True),
    sa.Column('bn', sa.String(length=200), nullable=True),
    sa.Column('my', sa.String(length=200), nullable=True),
    sa.Column('km', sa.String(length=200), nullable=True),
    sa.Column('pl', sa.String(length=200), nullable=True),
    sa.Column('cs', sa.String(length=200), nullable=True),
    sa.Column('uk', sa.String(length=200), nullable=True),
    sa.Column('sv', sa.String(length=200), nullable=True),
    sa.Column('sw', sa.String(length=200), nullable=True),
    sa.Column('ha', sa.String(length=200), nullable=True),
    sa.Column('zu', sa.String(length=200), nullable=True),
    sa.Column('am', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_am'), 'glossary_terms', ['am'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ar'), 'glossary_terms', ['ar'], unique=False)
    op.create_index(op.f('ix_glossary_terms_bn'), 'glossary_terms', ['bn'], unique=False)
    op.create_index(op.f('ix_glossary_terms_category'), 'glossary_terms', ['category'], unique=False)
    op.create_index(op.f('ix_glossary_terms_cs'), 'glossary_terms', ['cs'], unique=False)
    op.create_index(op.f('ix_glossary_terms_de'), 'glossary_terms', ['de'], unique=False)
    op.create_index(op.f('ix_glossary_terms_en'), 'glossary_terms', ['en'], unique=False)
    op.create_index(op.f('ix_glossary_terms_es'), 'glossary_terms', ['es'], unique=False)
    op.create_index(op.f('ix_glossary_terms_fa'), 'glossary_terms', ['fa'], unique=False)
    op.create_index(op.f('ix_glossary_terms_fr'), 'glossary_terms', ['fr'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ha'), 'glossary_terms', ['ha'], unique=False)
    op.create_index(op.f('ix_glossary_terms_he'), 'glossary_terms', ['he'], unique=False)
    op.create_index(op.f('ix_glossary_terms_hi'), 'glossary_terms', ['hi'], unique=False)
    op.create_index(op.f('ix_glossary_terms_id_ba'), 'glossary_terms', ['id_ba'], unique=False)
    op.create_index(op.f('ix_glossary_terms_it'), 'glossary_terms', ['it'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ja'), 'glossary_terms', ['ja'], unique=False)
    op.create_index(op.f('ix_glossary_terms_km'), 'glossary_terms', ['km'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ko'), 'glossary_terms', ['ko'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ms'), 'glossary_terms', ['ms'], unique=False)
    op.create_index(op.f('ix_glossary_terms_my'), 'glossary_terms', ['my'], unique=False)
    op.create_index(op.f('ix_glossary_terms_nl'), 'glossary_terms', ['nl'], unique=False)
    op.create_index(op.f('ix_glossary_terms_pl'), 'glossary_terms', ['pl'], unique=False)
    op.create_index(op.f('ix_glossary_terms_pt'), 'glossary_terms', ['pt'], unique=False)
    op.create_index(op.f('ix_glossary_terms_ru'), 'glossary_terms', ['ru'], unique=False)
    op.create_index(op.f('ix_glossary_terms_status'), 'glossary_terms', ['status'], unique=False)
    op.create_index(op.f('ix_glossary_terms_sv'), 'glossary_terms', ['sv'], unique=False)
    op.create_index(op.f('ix_glossary_terms_sw'), 'glossary_terms', ['sw'], unique=False)
    op.create_index(op.f('ix_glossary_terms_th'), 'glossary_terms', ['th'], unique=False)
    op.create_index(op.f('ix_glossary_terms_tl'), 'glossary_terms', ['tl'], unique=False)
    op.create_index(op.f('ix_glossary_terms_tr'), 'glossary_terms', ['tr'], unique=False)
    op.create_index(op.f('ix_glossary_terms_uk'), 'glossary_terms', ['uk'], unique=False)
    op.create_index(op.f('ix_glossary_terms_vi'), 'glossary_terms', ['vi'], unique=False)
    op.create_index(op.f('ix_glossary_terms_zh'), 'glossary_terms', ['zh'], unique=False)
    op.create_index(op.f('ix_glossary_terms_zu'), 'glossary_terms', ['zu'], unique=False)
    op.create_table('international_target_sites',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('crawl_interval', sa.Integer(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_target_sites_region'), 'international_target_sites', ['region'], unique=False)
    op.create_index(op.f('ix_international_target_sites_status'), 'international_target_sites', ['status'], unique=False)
    op.create_table('payment_channels',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_channels_channel'), 'payment_channels', ['channel'], unique=True)
    op.create_table('tenant_plans',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_sites', sa.Integer(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('max_ai_quota', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_plans_code'), 'tenant_plans', ['code'], unique=True)
    op.create_table('translation_tasks',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('completed_items', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_tasks_status'), 'translation_tasks', ['status'], unique=False)
    op.create_table('international_crawl_logs',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('site_id', _uuid_col(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('inquiries_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ip_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['international_target_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_crawl_logs_site_id'), 'international_crawl_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_international_crawl_logs_status'), 'international_crawl_logs', ['status'], unique=False)
    op.create_table('international_inquiries',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('source_site_id', _uuid_col(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('wechat', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('product_interest', sa.String(length=500), nullable=True),
    sa.Column('product_model', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.String(length=200), nullable=True),
    sa.Column('budget', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('inquiry_time', sa.String(length=100), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_site_id'], ['international_target_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_international_inquiries_customer_name'), 'international_inquiries', ['customer_name'], unique=False)
    op.create_index(op.f('ix_international_inquiries_email'), 'international_inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_international_inquiries_language'), 'international_inquiries', ['language'], unique=False)
    op.create_index(op.f('ix_international_inquiries_product_interest'), 'international_inquiries', ['product_interest'], unique=False)
    op.create_index(op.f('ix_international_inquiries_region'), 'international_inquiries', ['region'], unique=False)
    op.create_index(op.f('ix_international_inquiries_source_site_id'), 'international_inquiries', ['source_site_id'], unique=False)
    op.create_index(op.f('ix_international_inquiries_status'), 'international_inquiries', ['status'], unique=False)
    op.create_table('tenants',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('plan_id', _uuid_col(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_quota_used', sa.Integer(), nullable=False),
    sa.Column('storage_used', sa.Integer(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['tenant_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_plan_id'), 'tenants', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('translation_records',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('task_id', _uuid_col(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['translation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_records_status'), 'translation_records', ['status'], unique=False)
    op.create_index(op.f('ix_translation_records_task_id'), 'translation_records', ['task_id'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('tenant_id', _uuid_col(), nullable=False),
    sa.Column('plan_id', _uuid_col(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['tenant_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_plan_id'), 'tenant_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('user_id', _user_id_type(), nullable=False),
    sa.Column('tenant_id', _uuid_col(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tenants_tenant_id'), 'user_tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenants_user_id'), 'user_tenants', ['user_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('tenant_id', _uuid_col(), nullable=False),
    sa.Column('subscription_id', _uuid_col(), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_orders_channel'), 'payment_orders', ['channel'], unique=False)
    op.create_index(op.f('ix_payment_orders_order_no'), 'payment_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_subscription_id'), 'payment_orders', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_orders_tenant_id'), 'payment_orders', ['tenant_id'], unique=False)
    op.create_table('tenant_invoices',
    sa.Column('id', _uuid_col(), nullable=False),
    sa.Column('tenant_id', _uuid_col(), nullable=False),
    sa.Column('subscription_id', _uuid_col(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_invoices_status'), 'tenant_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_invoices_subscription_id'), 'tenant_invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_tenant_invoices_tenant_id'), 'tenant_invoices', ['tenant_id'], unique=False)
    op.add_column('inquiries', sa.Column('wechat', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_inquiries_wechat'), 'inquiries', ['wechat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiries_wechat'), table_name='inquiries')
    op.drop_column('inquiries', 'wechat')
    op.drop_index(op.f('ix_tenant_invoices_tenant_id'), table_name='tenant_invoices')
    op.drop_index(op.f('ix_tenant_invoices_subscription_id'), table_name='tenant_invoices')
    op.drop_index(op.f('ix_tenant_invoices_status'), table_name='tenant_invoices')
    op.drop_table('tenant_invoices')
    op.drop_index(op.f('ix_payment_orders_tenant_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_subscription_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_order_no'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_channel'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_user_tenants_user_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_tenant_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_plan_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_translation_records_task_id'), table_name='translation_records')
    op.drop_index(op.f('ix_translation_records_status'), table_name='translation_records')
    op.drop_table('translation_records')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_plan_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_international_inquiries_status'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_source_site_id'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_region'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_product_interest'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_language'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_email'), table_name='international_inquiries')
    op.drop_index(op.f('ix_international_inquiries_customer_name'), table_name='international_inquiries')
    op.drop_table('international_inquiries')
    op.drop_index(op.f('ix_international_crawl_logs_status'), table_name='international_crawl_logs')
    op.drop_index(op.f('ix_international_crawl_logs_site_id'), table_name='international_crawl_logs')
    op.drop_table('international_crawl_logs')
    op.drop_index(op.f('ix_translation_tasks_status'), table_name='translation_tasks')
    op.drop_table('translation_tasks')
    op.drop_index(op.f('ix_tenant_plans_code'), table_name='tenant_plans')
    op.drop_table('tenant_plans')
    op.drop_index(op.f('ix_payment_channels_channel'), table_name='payment_channels')
    op.drop_table('payment_channels')
    op.drop_index(op.f('ix_international_target_sites_status'), table_name='international_target_sites')
    op.drop_index(op.f('ix_international_target_sites_region'), table_name='international_target_sites')
    op.drop_table('international_target_sites')
    op.drop_index(op.f('ix_glossary_terms_zu'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_zh'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_vi'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_uk'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_tr'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_tl'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_th'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_sw'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_sv'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_status'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ru'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_pt'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_pl'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_nl'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_my'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ms'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ko'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_km'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ja'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_it'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_id_ba'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_hi'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_he'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ha'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_fr'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_fa'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_es'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_en'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_de'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_cs'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_category'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_bn'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_ar'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_am'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
